name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v0
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make Gradle wrapper executable
      run: chmod +x gradlew
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        body: |
          # Igbo Gospel Message Android App v${{ github.ref_name }}
          
          ## What's New
          - Professional Android app for @igbogospelmessage YouTube channel
          - Featured video section with latest content
          - Complete video playlist
          - Friday notifications for new uploads
          - Modern Material Design 3 interface
          
          ## Installation
          1. Download the APK file above
          2. Enable "Unknown Sources" in Android settings (if needed)
          3. Install the APK
          4. Launch the app and enjoy your gospel content!
          
          ## Features
          - 📱 Mobile-optimized interface
          - 🎬 High-quality video playback
          - 🔔 Smart Friday notifications
          - 🎨 Professional gospel-inspired design
          
          Built with ❤️ for spreading the Gospel in Igbo language
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}